name: Build macOS .app

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install py2app

      - name: Create setup.py
        run: |
          echo "from setuptools import setup

APP = ['spoofer.py']
OPTIONS = {
    'argv_emulation': True,
    'packages': ['PIL', 'numpy', 'piexif', 'tkinterdnd2'],
}
setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
" > setup.py

      - name: Build .app
        run: |
          python setup.py py2app

      - name: Zip .app
        run: |
          cd dist
          zip -r spoofer-macos.zip spoofer.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spoofer-macos
          path: dist/spoofer-macos.zip
