name: Build macOS .app

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow numpy piexif tkinterdnd2 py2app

      - name: Generate setup.py
        run: |
          echo "from setuptools import setup\n\nAPP = ['spoofer.py']\nOPTIONS = {\n    'argv_emulation': True,\n    'packages': ['PIL', 'numpy', 'piexif', 'tkinterdnd2'],\n}\n\nsetup(\n    app=APP,\n    options={'py2app': OPTIONS},\n    setup_requires=['py2app'],\n)" > setup.py

      - name: Build .app with py2app
        run: |
          python setup.py py2app

      - name: Zip .app
        run: |
          cd dist
          zip -r spoofer-macos.zip spoofer.app

      - name: Upload .app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: spoofer-macos
          path: dist/spoofer-macos.zip
